//"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o8c38ioXUuz
 */

//Background: #1F2937
// Main: #008087
// Secondary: #8BD77E
// Accent: #25AE8D
// Alert: #F9F871
import { RequestInit } from "next/dist/server/web/spec-extension/request";
import Simulator from "./SimulatorComponent";

function wait(duration: number): Promise<string> {
  return new Promise((resolve, reject) => {
    if (duration < 0) {
      return reject(new Error("Duration cannot be negative"));
    } else {
      setTimeout(() => {
        return resolve(`${duration}`);
      }, duration);
    }
  });
}
var env = process.env.NODE_ENV || "development";
function devOrProd(api_endpoint: string) {
  console.log(env);
  console.log(process.env.NODE_ENV);
  console.log(env === "development");
  console.log(
    (env === "development"
      ? "http://localhost:3000"
      : "http://darkalmanac.com") + api_endpoint
  );
  if (env === "development") return "http://localhost:3000" + api_endpoint;

  return "http://darkalmanac.com" + api_endpoint;
}

// const res = await fetch(devOrProd("/api?delay=25000"));

// const resJSON: { greeting: string } = await res.json();
// console.log(resJSON);

export default async function SimulatorParent() {
  return (
    <>
      <Simulator />
    </>
  );
}
