/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o8c38ioXUuz
 */

//Background: #1F2937
// Main: #008087
// Secondary: #8BD77E
// Accent: #25AE8D
// Alert: #F9F871
import Link from "next/link";
import Image from "next/image";

export default function Component() {
  return (
    <div className="dark flex flex-col min-h-screen bg-gray-900 text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <Image height={40} width={40} src="logo.svg" alt="logo" />
          <span className="ml-2 text-xl font-bold">Dark Almanac</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Articles
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 bg-gray-800 h-full">
        <section className="bg-gray-800 h-full">
          <div id="test" className="flex justify-between">
            <div className="bg-[#FF0000] w-1/3 m-2">
              <b>Class Selector/Perks</b>
              <div className="flex bg-green-800 h-1/2 w-full"></div>
            </div>
            <div className="bg-[#FF0000] w-1/3 m-2">
              <EquipmentDisplay />
            </div>
            <div className="bg-[#FF0000] w-1/3 m-2">
              <span className="p-1 bg-green-800">Details</span>
              <span className="p-1 bg-orange-200">Physical Damage</span>
              <span className="p-1 bg-blue-300">Magical Damage</span>
              <div className="flex bg-green-800 h-full w-full"></div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-800">
        <p className="text-xs text-gray-500">
          © 2024 Game Theory Craft. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            About Us
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Contact
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

/**
 * v0 by Vercel.
 * @see https://v0.dev/t/ydgoSU2IfFd
 */
//import { Button } from "@/components/ui/button"
import React from "react";

const EquipmentDisplay = () => {
  return (
    <div
      style={{
        display: "flex",
        backgroundColor: "red",
        minHeight: "50px",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          backgroundColor: "blue",
          minHeight: "500px",
          minWidth: "150px",
          margin: "10px",
          justifyContent: "center",
          flexWrap: "wrap",
          alignContent: "center",
        }}
      >
        <div
          style={{
            display: "flex",
            backgroundColor: "green",
            height: "80px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "orange",
            height: "140px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "yellow",
            height: "140px",
            width: "80px",
            margin: "10px",
            justifyContent: "space-between",
          }}
        >
          <div
            style={{
              position: "relative",
              left: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
          <div
            style={{
              position: "relative",
              right: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
        </div>
      </div>
    </div>
  );
};
