/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o8c38ioXUuz
 */

//Background: #1F2937
// Main: #008087
// Secondary: #8BD77E
// Accent: #25AE8D
// Alert: #F9F871
import Link from "next/link";
import {
  CardTitle,
  CardHeader,
  CardContent,
  Card,
} from "@/Component/components/ui/card";
import { SVGProps } from "react";

export default function Component() {
  return (
    <div className="dark flex flex-col min-h-screen bg-gray-900 text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <GamepadIcon className="h-6 w-6" />
          <span className="ml-2 text-xl font-bold">Dark Almanac</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Articles
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 bg-gray-800">
        <section className="py-12 md:py-24 lg:py-32 bg-gray-800">
          <div className="flex px-4 md:px-6 flex-row justify-between">
            <div className="bg-[#FF0000] w-96">
              <b>Rogue</b>
            </div>
            <div className="bg-[#FF0000] w-96">
              <EquipmentDisplay />
            </div>
            <div className="bg-[#FF0000] w-96">Test</div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-800">
        <p className="text-xs text-gray-500">
          © 2024 Game Theory Craft. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            About Us
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Contact
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function GamepadIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>
  );
}

function MicroscopeIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 1-2-2V6h6v4a2 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0-1-1H9a1 0-1 1v3" />
    </svg>
  );
}

function LightbulbIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  );
}

function UserIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0-4-4H9a4 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

/**
 * v0 by Vercel.
 * @see https://v0.dev/t/ydgoSU2IfFd
 */
//import { Button } from "@/components/ui/button"
import React from "react";

const EquipmentDisplay = () => {
  return (
    <div
      style={{
        display: "flex",
        backgroundColor: "red",
        minHeight: "50px",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          backgroundColor: "blue",
          minHeight: "500px",
          minWidth: "150px",
          margin: "10px",
          justifyContent: "center",
          flexWrap: "wrap",
          alignContent: "center",
        }}
      >
        <div
          style={{
            display: "flex",
            backgroundColor: "green",
            height: "80px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "orange",
            height: "140px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "yellow",
            height: "140px",
            width: "80px",
            margin: "10px",
            justifyContent: "space-between",
          }}
        >
          <div
            style={{
              position: "relative",
              left: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
          <div
            style={{
              position: "relative",
              right: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
        </div>
      </div>
    </div>
  );
};

// function Component() {
//   return (
//     `<div className="bg-[#1c1c1c] p-8 text-white">
//       <div className="flex gap-8">
//         <div className="flex flex-col items-center">
//           <div className="border-2 border-gray-700 p-4 rounded-full">
//             <div className="grid grid-cols-2 gap-2">
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 1"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 2"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 3"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 4"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 5"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//               <div className="border border-gray-600 p-2">
//                 <img
//                   alt="Slot 6"
//                   className="h-[50px] w-[50px] object-cover"
//                   height="50"
//                   src="/placeholder.svg"
//                   style={{
//                     aspectRatio: "50/50",
//                     objectFit: "cover",
//                   }}
//                   width="50"
//                 />
//               </div>
//             </div>
//           </div>
//           <div className="mt-4">
//             <h2 className="text-center text-lg font-semibold">Rogue</h2>
//             <ul className="mt-2">
//               <li>Strength: 4</li>
//               <li>Vigor: 5</li>
//               <li>Agility: 26</li>
//               <li>Dexterity: 25</li>
//               <li>Will: 10</li>
//               <li>Knowledge: 10</li>
//               <li>Resourcefulness: 25</li>
//               <li>Health: 75 / 75</li>
//             </ul>
//             <Button className="mt-4 w-full">Open Details</Button>
//           </div>
//         </div>
//         <div className="flex flex-col">
//           <div className="grid grid-cols-3 gap-4" />
//         </div>
//       </div>
//     </div>`
//   )
// }
