"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o8c38ioXUuz
 */

//Background: #1F2937
// Main: #008087
// Secondary: #8BD77E
// Accent: #25AE8D
// Alert: #F9F871
import Link from "next/link";
import Image from "next/image";
import {
  useAttributeValues,
  DisplayStats,
  StatEditor,
} from "@Component/ui/StatEditor";

//import { useAttributeValues } from "../../lib/hooks";

export default function Component() {
  const attributes = useAttributeValues();
  return (
    <div className="dark flex flex-col min-h-screen bg-gray-900 text-white">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <Image height={40} width={40} src="logo.svg" alt="logo" />
          <span className="ml-2 text-xl font-bold">Dark Almanac</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Articles
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 bg-gray-800 h-full">
        <div className="bg-gray-800 h-full">
          <div
            id="test"
            className="flex justify-between flex-col items-center lg:justify-content lg:items-start lg:flex-row"
          >
            <div className="lg:w-1/3 m-2">
              <b>Class Selector/Perks</b>
              <div className="flex flex-col flex-wrap w-full justify-center items-center">
                <div className="flex h-1/2 w-full items-center">
                  <div className="flex bg-blue-800 h-16 w-16 justify-center align-middle m-2"></div>
                  <h2 className="m-2">Rogue</h2>
                </div>
              </div>
              <div className="flex flex-wrap h-1/3 w-full">
                <div className="flex h-1/2 w-1/2 justify-center items-center mt-2">
                  <div className="flex bg-green-800 h-24 w-24 justify-center align-middle"></div>
                </div>
                <div className="flex h-1/2 w-1/2 justify-center items-center mt-2">
                  <div className="flex bg-green-800 h-24 w-24 justify-center align-middle"></div>
                </div>
                <div className="flex h-1/2 w-1/2 justify-center items-center mt-2">
                  <div className="flex bg-green-800 h-24 w-24 justify-center align-middle"></div>
                </div>
                <div className="flex h-1/2 w-1/2 justify-center items-center mt-2">
                  <div className="flex bg-green-800 h-24 w-24 justify-center align-middle"></div>
                </div>
              </div>
              <div className="flex">
                <StatEditor attributes={attributes} />
              </div>
            </div>
            <div className="w-full lg:w-1/3 m-2">
              <EquipmentDisplay />
            </div>
            <div className="w-full lg:w-1/3 m-2">
              <div className="flex-1 grow">
                <span className="p-1 bg-green-800">Details</span>
                <span className="p-1 bg-orange-200">Physical Damage</span>
                <span className="p-1 bg-blue-300">Magical Damage</span>
              </div>

              <div className="flex-1">
                <DisplayStats attributes={attributes} />
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-800">
        <p className="text-xs text-gray-500">
          © 2024 Game Theory Craft. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            About Us
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Contact
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

/**
 * v0 by Vercel.
 * @see https://v0.dev/t/ydgoSU2IfFd
 */
//import { Button } from "@/components/ui/button"
import React from "react";
import { Z_VERSION_ERROR } from "zlib";

const EquipmentDisplay = () => {
  return (
    <div
      style={{
        display: "flex",
        minHeight: "50px",
        justifyContent: "center",
      }}
      className="flex justify-center"
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          backgroundColor: "blue",
          minHeight: "500px",
          minWidth: "150px",
          margin: "10px",
          justifyContent: "center",
          flexWrap: "wrap",
          alignContent: "center",
        }}
      >
        <div
          style={{
            display: "flex",
            backgroundColor: "green",
            height: "80px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "orange",
            height: "140px",
            width: "80px",
            margin: "10px",
          }}
        ></div>
        <div
          style={{
            display: "flex",
            backgroundColor: "yellow",
            height: "140px",
            width: "80px",
            margin: "10px",
            justifyContent: "space-between",
          }}
        >
          <div
            style={{
              position: "relative",
              left: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
          <div
            style={{
              position: "relative",
              right: "-40px",
              display: "flex",
              backgroundColor: "purple",
              height: "30px",
              width: "30px",
            }}
          ></div>
        </div>
      </div>
    </div>
  );
};
